### ISSUE TITLE
Remove `Text.Parsing` module prefix

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/purescript-string-parsers#78]
To go along with https://github.com/purescript-contrib/purescript-parsing/issues/147 -- this library could just as well do with just using `StringParser` as the module prefix, rather than including `Text.Parsing`, as we don't follow the Haskell example of putting all text-related packages under a `Text` grouping.

**Comment by chtenb** [comment]
While we're at it we might as well update the module structure a bit. Since this is a very simple package I think it would make sense to have a single module act as the main API, reexporting from Combinators and CodePoints, similarly to purescript-strings (see https://github.com/purescript/purescript-strings/blob/master/src/Data/String.purs)

**Comment by chtenb** [comment]
@thomashoneyman  What is the attitude towards these kind of changes in the PureScript ecosystem? Should we just do this the next time we push a breaking change? This would be the next release.

**Comment by chtenb** [comment]
Is there a particular reason we don't use the Text namespace anymore by the way? Or put another way, do we have a formal set of guidelines about module names somewhere?
